version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - qdrant
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434
      - OLLAMA_MODEL=deepseek-r1:8b
      - HOST=0.0.0.0
      - PORT=8000
      - DOCKER_CONTAINER=true
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_BASE_URL=${JIRA_BASE_URL}
      - JIRA_PROJECT_ID=${JIRA_PROJECT_ID}
      - QDRANT_HOST=qdrant

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  # The Qdrant server already includes a dashboard at /dashboard path
  # You can access it directly at http://localhost:6333/dashboard

volumes:
  qdrant_data:
